### ISSUE TITLE
plugin failed to load

### ISSUE THREAD

**Issue by ktmtrash** [ToppleKek/discord-rhythmbox-plugin#12]
after adding the plugin for the first it worked flawlessly but then after closing rhythmbox and opening it again made the plugin not work
[a similar error from someone else](https://unix.stackexchange.com/questions/643268/rhythmbox-not-detecting-plugin-discord-rhythmbox-plugin)
![2021-07-31_17-55](https://user-images.githubusercontent.com/88025515/127739458-48d29da0-3ab6-48da-8d2e-c5c42f8276e1.png)

**Comment by ToppleKek** [comment]
Please run Rhythmbox from a terminal and post the output. You should see a line similar to:
`** (rhythmbox:42499): WARNING **: 16:41:42.710: Error importing plugin 'discord-status':`
then post the error it gives.

**Comment by ktmtrash** [comment]
it gave this error

** (rhythmbox:75053): WARNING **: 07:40:35.440: Error importing plugin 'discord-status':
Traceback (most recent call last):
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 10, in <module>
    from status_prefs import discord_status_prefs
  File "/usr/lib/rhythmbox/plugins/discord-rhythmbox-plugin/status_prefs.py", line 6, in <module>
    import rb
ModuleNotFoundError: No module named 'rb'

(rhythmbox:75053): libpeas-WARNING **: 07:40:35.440: Error loading plugin 'discord-status'

**Comment by ToppleKek** [comment]
That import isn't even required (copy paste error, oops). Try removing the `import rb` line or update the plugin with the latest commit.

**Comment by ktmtrash** [comment]
It's working now ^^, by the way is here some way to show the elapsed time instead of remaining time on the status?

**Comment by ToppleKek** [comment]
Yeah I can definitely add that when I get the chance this week.

**Comment by ktmtrash** [comment]
Looking forward to it!
