### ISSUE TITLE
Doesn't work after updating to Python 3.10

### ISSUE THREAD

**Issue by Ruthenic** [ToppleKek/discord-rhythmbox-plugin#14]
this only started happening after an update to python 3.10 from my distro.  
error log as follows:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ruthenic/.local/share/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 13, in <module>
    class discord_status_dev(GObject.Object, Peas.Activatable):
  File "/home/ruthenic/.local/share/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 33, in discord_status_dev
    RPC.connect()
  File "/home/ruthenic/.local/lib/python3.10/site-packages/pypresence/presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/ruthenic/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 128, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.10/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
TypeError: _UnixSelectorEventLoop.create_unix_connection() got an unexpected keyword argument 'loop'```

**Comment by Ruthenic** [comment]
After taking a close look at the log, this may actually be an issue with pypresence? I'm not entirely sure though, so i'll leave it open

**Comment by ToppleKek** [comment]
Sorry for the extremely late reply, but yes this does appear to be a problem with pypresence... Not sure if they have fixed this yet but that will be up to them.
