### ISSUE TITLE
Ubuntu Budgie 18.04 Failed to Load

### ISSUE THREAD

**Issue by MrAureliusR** [ToppleKek/discord-rhythmbox-plugin#2]
Followed instructions, installed pypresence (for both python 2 and 3, not sure which version this uses). Cloned folder into /usr/share/rhythmbox/plugins (I also tried it in ~/.local/share/rhythmbox/plugins, same result). Open plugins, click the checkbox, get exclamation mark. Hovering over the exclamation mark gives the extremely useful error "Failed to load".

Does this log somewhere? I'd be happy to help debug this if I knew where/if it was logging.

**Comment by MrAureliusR** [comment]
I was unable to get it working with your method, can you be a bit more clear about the steps you took? I tried opening RB, enabling and disabling im-status, restarting RB and then trying to enable Discord but that still gives the same error. I am actually getting a different error on the command line, as follows:

```(rhythmbox:23124): libpeas-WARNING **: 12:28:34.783: Error importing plugin 'discord-status':
Traceback (most recent call last):
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 9, in <module>
    class discord_status (GObject.Object, Peas.Activatable):
  File "/usr/lib/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 11, in discord_status
    RPC.connect()
  File "/home/amr/.local/lib/python3.6/site-packages/pypresence/presence.py", line 123, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/amr/.local/lib/python3.6/site-packages/pypresence/presence.py", line 58, in handshake
    self.sock_reader, self.sock_writer = yield from asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/streams.py", line 134, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 245, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 455, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

(rhythmbox:23124): libpeas-WARNING **: 12:28:34.783: Error loading plugin 'discord-status'```

**Comment by ToppleKek** [comment]
Attempt to fix it, that issue that you're having now seems to be something to do with pypresence, did you install it as root or not?

**Comment by MrAureliusR** [comment]
Originally installed not as root, I just tried to install it as root and it says requirements already satisfied, so I removed pypresence and tried to reinstall, but it's still saying it's already installed. Going to try and figure this out first... pip can be such a headache sometimes.

**Comment by ToppleKek** [comment]
Alright, if nothing else works you can try installing the latest pypresence with `pip install https://github.com/qwertyquerty/pypresence/archive/master.zip` not sure whats happening here.

**Comment by MrAureliusR** [comment]
Okay, figured it out. I removed pypresence as both sudo and non-sudo, then installed only as sudo. I can confirm the files are in the correct places. Still getting the same error though. I will attempt to install the latest version as you just recommended.

**Comment by ToppleKek** [comment]
I'm just as confused as you, I don't know what it's looking for lol. I'm gonna make an Ubuntu VM real quick and see if I get the same issue...

**Comment by MrAureliusR** [comment]
Alright. Let me know if you wanna take a look at this system, I will send the VNC password and IP.

**Comment by ToppleKek** [comment]
Don't think I'll have to do that, I get the same error in an ubuntu vm, but it loads fine on my debian sid laptop... I think I'll go submit an issue to pypresence, sorry for the wait!

**Comment by ToppleKek** [comment]
Did you have discord open when you tried? I was able to sign into discord on my vm and have it work. Using the latest canary.

**Comment by ToppleKek** [comment]
Assuming this is solved.
