### ISSUE TITLE
After months of using the plugin, it broke

### ISSUE THREAD

**Issue by SpaceboyRoss01** [ToppleKek/discord-rhythmbox-plugin#5]
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 11, in <module>
    class discord_status_dev (GObject.Object, Peas.Activatable):
  File "/usr/lib/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 18, in discord_status_dev
    Notify.Notification.new("Rhythmbox Discord Status Plugin", "Connected to Discord").show()
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
```

**Comment by ToppleKek** [comment]
Check out latest commit, that happens when it can't send notifications. Now it should skip the notifications if it can't initialize.

**Comment by SpaceboyRoss01** [comment]
I already updated it

**Comment by ToppleKek** [comment]
Did that solve it?

**Comment by SpaceboyRoss01** [comment]
Nope

**Comment by ToppleKek** [comment]
Is it the same error? Post it again.

**Comment by SpaceboyRoss01** [comment]
That's the error I got after updating it.

```
(rhythmbox:11746): libpeas-WARNING **: 13:39:27.205: Error importing plugin 'discord-status':
Traceback (most recent call last):
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 11, in <module>
    class discord_status_dev (GObject.Object, Peas.Activatable):
  File "/usr/lib/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 18, in discord_status_dev
    Notify.Notification.new("Rhythmbox Discord Status Plugin", "Connected to Discord").show()
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
```

**Comment by ToppleKek** [comment]
Are you sure you updated it? Because like 18 doesn't say that anymore...

**Comment by SpaceboyRoss01** [comment]
Yup, git clone

**Comment by SpaceboyRoss01** [comment]
re re updated it and the message changed.

**Comment by ToppleKek** [comment]
Well? What is it now?

**Comment by SpaceboyRoss01** [comment]
```
Failed to init Notify. Is the notificaion service running?

(rhythmbox:12006): Rhythmbox-WARNING **: 13:42:19.217: Unable to grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.MediaKeys was not provided by any .service files
```

**Comment by ToppleKek** [comment]
It should be working fine now, that's just a message that gets shown instead of it erroring out.

**Comment by devnullul** [comment]
Can confirm updating fixes it, I had this same issue and updated and now it works fine
